module.exports = {
  UPDATE_RESERVATION: "UPDATE_RESERVATION",
  DELETE_RESERVATION: "DELETE_RESERVATION",
  READ_NOTIFICATION: "READ_NOTIFICATION",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
  DELETE_NOTIFICATIONS_BY_ROOM: "DELETE_NOTIFICATIONS_BY_ROOM",
  ASSIGN_RESPONSABLE: "ASSIGN_RESPONSABLE",
  UPDATE_ROOM: "UPDATE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  CREATE_RESERVATION: "CREATE_RESERVATION",
  VALIDATE_RESERVATION: "VALIDATE_RESERVATION"
};